/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import conexion.ConectorTCP;
import dialog.CrudTarea;
import entidades.Tarea;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.CallbackRespuesta;
import util.Util;

/**
 *
 * @author agarcia.gonzalez
 */
public class PanelTareas extends javax.swing.JDialog {

    private PaneEdiccion parent;
    private DefaultTableModel model;
    
    
    public PanelTareas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = (PaneEdiccion) parent;
        
        this.setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tablaTarea.getModel();
        
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        ConectorTCP.getInstance().realizarConexion("getAllTareas", null, new CallbackRespuesta() {
            @Override
            public void success(Map<String, String> contenido) {
                model.setRowCount(0);   // Reiniciamos el contenido de la tabla
                
                List<Tarea> lista = util.Util.convertMapToList(Tarea.class, contenido);
                
                for (Tarea s : lista) {
                    parent.addRowToTable(model, new Object[] {
                        s.getId(),
                        s.getNombre(),
                        s.getObservaciones(),
                        s.getEstimacion()
                    });
                }
            }

            @Override
            public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                System.out.println("ERROR: " + contenido.get("error"));
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTarea = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTarea = new javax.swing.JTable();
        botonCrear = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGenerarTareas = new javax.swing.JButton();
        botonAsignarTareas = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));

        panelTarea.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tareas");

        tablaTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Observacion", "Estimacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaTarea);

        botonCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonCrear.setText("Crear tarea");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEliminar.setText("Eliminar tarea");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonGenerarTareas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonGenerarTareas.setText("Generar tareas");
        botonGenerarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarTareasActionPerformed(evt);
            }
        });

        botonAsignarTareas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonAsignarTareas.setText("Asignar tareas auto");
        botonAsignarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarTareasActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEditar.setText("Editar tarea");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTareaLayout = new javax.swing.GroupLayout(panelTarea);
        panelTarea.setLayout(panelTareaLayout);
        panelTareaLayout.setHorizontalGroup(
            panelTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTareaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTareaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonGenerarTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonAsignarTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelTareaLayout.setVerticalGroup(
            panelTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(panelTareaLayout.createSequentialGroup()
                        .addComponent(botonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGenerarTareas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAsignarTareas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        abrirCreacionTarea();
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        eliminarTarea();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonGenerarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarTareasActionPerformed
        generarTareas ();
    }//GEN-LAST:event_botonGenerarTareasActionPerformed

    private void botonAsignarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarTareasActionPerformed
        asignarTareasAutomaticamente ();
    }//GEN-LAST:event_botonAsignarTareasActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        abrirEdiccionTarea();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void abrirCreacionTarea() {
        CrudTarea crud = new CrudTarea (parent, this, true, false, 0);
        crud.setVisible(true);
    }
    
    private void abrirEdiccionTarea() {
        int id = tablaTarea.getSelectedRow();
        
        if (id>=0) {
            String rowId = tablaTarea.getValueAt(id, 0).toString();
            
            int seleccionado = Integer.parseInt(rowId);
            
            System.out.println("SELECCIONADO: " + seleccionado);
            
            CrudTarea crud = new CrudTarea (parent, this, true, true, seleccionado);
            crud.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No tienes seleccionado ninguna tarea");
        }
    }
    
    private void eliminarTarea () {
        int id = tablaTarea.getSelectedRow();
        
        if (id>=0) {
            int eleccion = JOptionPane.showConfirmDialog(parent, "Quieres eliminar esta tarea?");
            if (eleccion==0) {
                String rowId = tablaTarea.getValueAt(id, 0).toString();
            
                int seleccionado = Integer.parseInt(rowId);
                
                Map<String,String> parametros = new HashMap<String,String>();
                parametros.put("id", seleccionado+"");
                
                ConectorTCP.getInstance().realizarConexion("deleteTarea", parametros, new CallbackRespuesta() {
                    @Override
                    public void success(Map<String, String> contenido) {
                        JOptionPane.showMessageDialog(null, "Se ha eliminado la tarea");
                        actualizarTabla();
                    }

                    @Override
                    public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                        JOptionPane.showMessageDialog(null, "No se ha podido eliminar la tarea: " + contenido.get("error"));
                    }
                    
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "No tienes seleccionado ninguna tarea");
        }
    }
    
    private void generarTareas () {
        int eleccion = JOptionPane.showConfirmDialog(parent, "Quieres generar tareas automaticamente?");
        if (eleccion==0) {
            Map<String,String> parametros = new HashMap<String,String>();
            ConectorTCP.getInstance().realizarConexion("generarTareas", parametros, new CallbackRespuesta() {
                @Override
                public void success(Map<String, String> contenido) {
                    JOptionPane.showMessageDialog(null, "Se han generado las tareas satisfactoriamente");
                    actualizarTabla();
                }

                @Override
                public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                    JOptionPane.showMessageDialog(null, "No se ha generar las tareas: " + contenido.get("error"));
                }
            });
        }
    }
    
    private void asignarTareasAutomaticamente () {
        int eleccion = JOptionPane.showConfirmDialog(parent, "Quieres asignar las tareas automaticamente?");
        if (eleccion==0) {
            Map<String,String> parametros = new HashMap<String,String>();
            ConectorTCP.getInstance().realizarConexion("asignarTareas", parametros, new CallbackRespuesta() {
                @Override
                public void success(Map<String, String> contenido) {
                    JOptionPane.showMessageDialog(null, "Las tareas se han asignado correctamente");
                    actualizarTabla();
                }

                @Override
                public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                    JOptionPane.showMessageDialog(null, "No se ha podido asignar las tareas: " + contenido.get("error"));
                    actualizarTabla();
                }
            });
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignarTareas;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGenerarTareas;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelTarea;
    private javax.swing.JTable tablaTarea;
    // End of variables declaration//GEN-END:variables
}
