/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import conexion.ConectorTCP;
import dialog.CrudEmpleado;
import entidades.Empleado;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.CallbackRespuesta;
import util.Util;

/**
 *
 * @author agarcia.gonzalez
 */
public class PanelEmpleados extends javax.swing.JDialog {

    private PaneEdiccion parent;
    private DefaultTableModel model;
    
    /**
     * Creates new form PanelEmpleados
     */
    public PanelEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = (PaneEdiccion) parent;
        
        this.setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tablaEmpleados.getModel();
        
        actualizarTabla();
    }
    
    public void actualizarTabla() {
        ConectorTCP.getInstance().realizarConexion("getEmpleados", null, new CallbackRespuesta() {
            @Override
            public void success(Map<String, String> contenido) {
                model.setRowCount(0);   // Reiniciamos el contenido de la tabla
                
                List<Empleado> lista = util.Util.convertMapToList(Empleado.class, contenido);
                
                for (Empleado e : lista) {
                    parent.addRowToTable(model, new Object[] {
                        e.getId(),
                        e.getNombre() + " " + e.getApellido1() + ((e.getApellido2()!=null) ? " " + e.getApellido2() : ""),
                        "Desconocido",
                        e.getDireccion()
                    });
                }
                
            }

            @Override
            public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                System.out.println("ERROR: " + contenido.get("error"));
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmpleado1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        botonNuevo = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonDarBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));

        panelEmpleado1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Empleados");

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Puesto", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaEmpleados);

        botonNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonNuevo.setText("Nuevo empleado");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEditar.setText("Editar empleado");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEliminar.setText("Eliminar empleado");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonDarBaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonDarBaja.setText("Dar baja empleado");
        botonDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEmpleado1Layout = new javax.swing.GroupLayout(panelEmpleado1);
        panelEmpleado1.setLayout(panelEmpleado1Layout);
        panelEmpleado1Layout.setHorizontalGroup(
            panelEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpleado1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEmpleado1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(botonDarBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelEmpleado1Layout.setVerticalGroup(
            panelEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(panelEmpleado1Layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDarBaja)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        abrirCreacionEmpleado();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        abrirEdiccionEmpleado();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        eliminarEmpleado();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDarBajaActionPerformed
        darBajaEmpleado();
    }//GEN-LAST:event_botonDarBajaActionPerformed

    private void abrirEdiccionEmpleado() {
        int id = tablaEmpleados.getSelectedRow();
        
        if (id>=0) {
            String rowId = tablaEmpleados.getValueAt(id, 0).toString();
            
            int seleccionado = Integer.parseInt(rowId);
            
            System.out.println("SELECCIONADO: " + seleccionado);
            
            CrudEmpleado crud = new CrudEmpleado (parent, this, true, true, seleccionado);
            crud.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No tienes seleccionado ningún empleado");
        }
    }
    
    private void abrirCreacionEmpleado () {
        CrudEmpleado crud = new CrudEmpleado (parent, this, true, false, 0);
        crud.setVisible(true);
    }
    
    private void eliminarEmpleado () {
        int id = tablaEmpleados.getSelectedRow();
        
        if (id>=0) {
            int eleccion = JOptionPane.showConfirmDialog(parent, "Quieres eliminar este empleado?");
            if (eleccion==0) {
                String rowId = tablaEmpleados.getValueAt(id, 0).toString();
            
                int seleccionado = Integer.parseInt(rowId);
                
                Map<String,String> parametros = new HashMap<String,String>();
                parametros.put("id", seleccionado+"");
                
                ConectorTCP.getInstance().realizarConexion("deleteEmpleado", parametros, new CallbackRespuesta() {
                    @Override
                    public void success(Map<String, String> contenido) {
                        JOptionPane.showMessageDialog(null, "Se ha eliminado el empleado");
                        actualizarTabla();
                    }

                    @Override
                    public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                        JOptionPane.showMessageDialog(null, "No se ha podido eliminar el empleado: " + contenido.get("error"));
                    }
                    
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "No tienes seleccionado ningún empleado");
        }
    }
    
    private void darBajaEmpleado () {
        int id = tablaEmpleados.getSelectedRow();
        
        if (id>=0) {
            int eleccion = JOptionPane.showConfirmDialog(parent, "Quieres dar de baja a este empleado?");
            if (eleccion==0) {
                String rowId = tablaEmpleados.getValueAt(id, 0).toString();
            
                int seleccionado = Integer.parseInt(rowId);
                
                Map<String,String> parametros = new HashMap<String,String>();
                parametros.put("id", seleccionado+"");
                
                ConectorTCP.getInstance().realizarConexion("bajaEmpleado", parametros, new CallbackRespuesta() {
                    @Override
                    public void success(Map<String, String> contenido) {
                        JOptionPane.showMessageDialog(null, "Se ha dado de baja al empleado");
                        actualizarTabla();
                    }

                    @Override
                    public void error(Map<String, String> contenido, Util.CODIGO codigoError) {
                        JOptionPane.showMessageDialog(null, "No se ha podido dar de baja al empleado: " + contenido.get("error"));
                    }
                    
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "No tienes seleccionado ningún empleado");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDarBaja;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelEmpleado1;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
